log_level: info
no_log_file: false
no_progress: true
package:
    create:
        max_package_size: 0
        set: {}
        skip_sbom: true
    deploy:
        components: "podinfo"
        set: {}
